# Generated by Django 4.1.7 on 2023-02-26 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='lasr_name',
            new_name='last_name',
        ),
    ]
